model_list:
  - model_name: claude-sonnet-4
    litellm_params:
      model: "bedrock/converse/us.anthropic.claude-sonnet-4-20250514-v1%3A0"
      aws_access_key_id: "AWS"
      aws_secret_access_key: "AWS"
      aws_region_name: "us-west-2"
      aws_bedrock_runtime_endpoint: "https://api.ai.public.rakuten-it.com/aws-bedrock/v1"
      extra_headers:
        Authorization: "os.environ/RAKUTEN_AI_API_KEY"
  - model_name: claude-3-7-sonnet-direct
    litellm_params:
      model: "anthropic/claude-3-7-sonnet-20250219"
      api_base: "https://api.ai.public.rakuten-it.com/anthropic/v1"
      api_key: "os.environ/RAKUTEN_AI_API_KEY"
      extra_headers:
        Authorization: "os.environ/RAKUTEN_AI_API_KEY"
        anthropic-version: "2023-06-01"
        content-type: "application/json"
  - model_name: gemini-2.5-pro
    litellm_params:
      model: "openai/google/gemini-2.5-pro"
      api_base: "https://api.ai.public.rakuten-it.com/google-vertexai-us/oai-spec/v1/"
      api_key: "os.environ/RAKUTEN_AI_API_KEY"
      extra_headers:
        Authorization: "os.environ/RAKUTEN_AI_API_KEY"
  - model_name: gpt-4.1
    litellm_params:
      model: "openai/gpt-4.1"
      api_base: "https://api.ai.public.rakuten-it.com/openai/v1/chat/completions"
      api_key: "os.environ/RAKUTEN_AI_API_KEY"
      extra_headers:
        Authorization: "Bearer os.environ/RAKUTEN_AI_API_KEY"
  - model_name: gpt-4o-mini-tts
    litellm_params:
      model: "openai/gpt-4o-mini-tts"
      api_base: "https://api.ai.public.rakuten-it.com/openai/v1"
      api_key: "os.environ/RAKUTEN_AI_API_KEY"
      extra_headers:
        Authorization: "Bearer os.environ/RAKUTEN_AI_API_KEY"
  - model_name: gpt-4o-transcribe
    litellm_params:
      model: "openai/gpt-4o-transcribe"
      api_base: "https://api.ai.public.rakuten-it.com/openai/v1"
      api_key: "os.environ/RAKUTEN_AI_API_KEY"
      extra_headers:
        Authorization: "Bearer os.environ/RAKUTEN_AI_API_KEY"

litellm_settings:
  drop_params: true
